export default [
  {
    adult: false,
    backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
    genre_ids: [28, 878, 35, 10751],
    id: 939243,
    original_language: "en",
    original_title: "Sonic the Hedgehog 3",
    overview:
      '너클즈, 테일즈와 함께 평화로운 일상을 보내던 초특급 히어로 소닉. 연구 시설에 50년간 잠들어 있던 사상 최강의 비밀 병기 "섀도우"가 탈주하자, 세계 수호 통합 부대(약칭 세.수.통)에 의해 극비 소집된다. 소중한 것을 잃은 분노와 복수심에 불타는 섀도우는 소닉의 초고속 스피드와 너클즈의 최강 펀치를 단 단숨에 제압해버린다. 세상을 지배하려는 닥터 로보트닉과 그의 할아버지 제럴드 박사는 섀도우의 엄청난 힘 카오스 에너지를 이용해 인류를 정복하려고 하는데…',
    popularity: 3088.942,
    poster_path: "/5ZoI48Puf5i5FwI6HOpunDuJOw0.jpg",
    release_date: "2024-12-19",
    title: "수퍼 소닉 3",
    video: false,
    vote_average: 7.6,
    vote_count: 528,
  },
  {
    adult: false,
    backdrop_path: "/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
    genre_ids: [28, 12, 18],
    id: 558449,
    original_language: "en",
    original_title: "Gladiator II",
    overview:
      "로마의 영웅이자 최고의 검투사였던 막시무스가 콜로세움에서 죽음을 맞이한 뒤 20여 년이 흐른 후. 쌍둥이 황제 게타와 카라칼라의 폭압 아래 시민을 위한 자유로운 나라 로마의 꿈은 잊힌 지 오래다. 한편 아카시우스 장군이 이끄는 로마군에 대패한 후 모든 것을 잃고 노예로 전락한 루시우스는 강한 권력욕을 지닌 마크리누스의 눈에 띄어 검투사로 발탁된다. 로마를 향한 걷잡을 수 없는 분노, 타고난 투사의 기질로 콜로세움에 입성하게 된 루시우스는 결투를 거듭하며 자신이 진짜 누구인지 알게 되고 마침내 로마의 운명을 건 결전을 준비하게 되는데...!",
    popularity: 2793.693,
    poster_path: "/b5UXjzW5cLZhprMnlAmsVAA3G4t.jpg",
    release_date: "2024-11-05",
    title: "글래디에이터 II",
    video: false,
    vote_average: 6.8,
    vote_count: 2281,
  },
  {
    adult: false,
    backdrop_path: "/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg",
    genre_ids: [12, 10751, 16],
    id: 762509,
    original_language: "en",
    original_title: "Mufasa: The Lion King",
    overview:
      "길을 잃고 혼자가 된 새끼 사자 무파사는 광활한 야생을 떠돌던 중 왕의 혈통이자 예정된 후계자 타카와 우연히 만나게 된다. 마치 친형제처럼 끈끈한 우애를 나누며 함께 자란 무파사와 타카는 운명을 개척하기 위해 거대한 여정을 함께 떠난다. 한 치 앞을 알 수 없는 적들의 위협 속에서 두 형제의 끈끈했던 유대에 금이 가기 시작하고 예상치 못한 위기까지 맞닥뜨리게 되는데…",
    popularity: 2932.613,
    poster_path: "/1VUExee8iFohFTwYVi4IOArYyaM.jpg",
    release_date: "2024-12-18",
    title: "무파사: 라이온 킹",
    video: false,
    vote_average: 7.4,
    vote_count: 625,
  },
  {
    adult: false,
    backdrop_path: "/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg",
    genre_ids: [28, 878, 12],
    id: 912649,
    original_language: "en",
    original_title: "Venom: The Last Dance",
    overview:
      "환상의 케미스트리의 에디 브록과 그의 심비오트 베놈은 그들을 노리는 정체불명 존재의 추격을 피해 같이 도망을 다니게 된다. 한편 베놈의 창조자 널은 고향 행성에서부터 그들을 찾아내기 위해 지구를 침략하고 에디와 베놈은 그동안 겪어보지 못한 최악의 위기를 맞이하게 되는데…",
    popularity: 2258.338,
    poster_path: "/3flIDcZF3tnR7m5OU2h7lLPQwmr.jpg",
    release_date: "2024-10-22",
    title: "베놈: 라스트 댄스",
    video: false,
    vote_average: 6.815,
    vote_count: 2326,
  },
  {
    adult: false,
    backdrop_path: "/vYqt6kb4lcF8wwqsMMaULkP9OEn.jpg",
    genre_ids: [16, 12, 10751, 35],
    id: 1241982,
    original_language: "en",
    original_title: "Moana 2",
    overview:
      "바다를 누볐던 선조들에게서 예기치 못한 부름을 받은 모아나가 마우이와 다시 만나 새로운 선원들과 함께 오랫동안 잊혀진 멀고 위험한 바다 너머로 떠나는 특별한 모험을 담은 이야기",
    popularity: 1994.752,
    poster_path: "/2WVvPcVRqfjyVzIUVIcszGb6zT4.jpg",
    release_date: "2024-11-21",
    title: "모아나 2",
    video: false,
    vote_average: 7,
    vote_count: 838,
  },
  {
    adult: false,
    backdrop_path: "/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",
    genre_ids: [18, 10749, 14],
    id: 402431,
    original_language: "en",
    original_title: "Wicked",
    overview:
      "자신의 진정한 힘을 아직 발견하지 못한 엘파바와 자신의 진정한 본성을 발견하지 못한 글린다, 전혀 다른 두 인물이 우정을 쌓아가며 맞닥뜨리는 예상치 못한 위기와 모험을 그린 이야기",
    popularity: 1592.229,
    poster_path: "/mHozMgx7w29qC9gLzUQDQEP7AEM.jpg",
    release_date: "2024-11-20",
    title: "위키드",
    video: false,
    vote_average: 7.2,
    vote_count: 1235,
  },
  {
    adult: false,
    backdrop_path: "/cjEcqdRdPQJhYre3HUAc5538Gk8.jpg",
    genre_ids: [28, 14, 35],
    id: 845781,
    original_language: "en",
    original_title: "Red One",
    overview:
      "크리스마스 D-1, 철통같은 보안을 뚫고 코드명 '레드 원' 산타클로스가 납치되고 크리스마스가 사라질 위기에 처했다! '레드 원'을 찾기 위해 사령관 '칼럼 드리프트'는 산타클로스 따위는 없다고 믿는 현상금 사냥꾼 '잭 오말리'와 협력하기로 한다. 시작부터 삐그덕 거리는 이들 앞에 크리스마스의 존재를 위협하는 위험천만한 적들이 나타나는데…",
    popularity: 1533.747,
    poster_path: "/4zNUNhVpSqFggxqvdSXDRzy1QwE.jpg",
    release_date: "2024-10-31",
    title: "레드 원",
    video: false,
    vote_average: 7.065,
    vote_count: 1995,
  },
  {
    adult: false,
    backdrop_path: "/ie8OSgIHEl6yQiGJ90dsyBWOpQA.jpg",
    genre_ids: [16, 14, 28, 12],
    id: 839033,
    original_language: "en",
    original_title: "The Lord of the Rings: The War of the Rohirrim",
    overview:
      "로한의 전설적인 왕 무쇠주먹 ‘헬름’은 공주 ‘헤라’와 자신의 아들 ‘울프’와의 결혼을 요구하는 웨스트마크 영주인 ‘프레카’와 결투를 벌이다 예기치 않게 그를 죽이고 만다. 아버지의 죽음에 격분하여 복수를 다짐하고 사라진 ‘울프’. 어느 날, 그는 무자비한 던랜드인을 이끌고 나타나 로한을 공격한다. ‘헬름’과 그의 아들 ‘할레스’와 ‘하마’, 그리고 기마대 로히림이 공격에 맞서지만 영주들의 배신으로 크게 패배하며 나팔 산성으로 퇴각하게 된다. ‘할레스’와 ‘하마’ 두 왕자를 모두 잃은 ‘헬름’과 ‘헤라’는 ‘울프’와 대규모 던랜드 군대에 의해 나팔 산성에 고립된 상황에서 모두의 목숨을 건 마지막 전투를 준비한다.",
    popularity: 1421.283,
    poster_path: "/eeN1fRy5UjTwtTQTz1EdVaE5aC.jpg",
    release_date: "2024-12-05",
    title: "반지의 제왕: 로히림의 전쟁",
    video: false,
    vote_average: 6.5,
    vote_count: 300,
  },
  {
    adult: false,
    backdrop_path: "/fzjH7kt1017R9EckLDmWmH5pGhD.jpg",
    genre_ids: [28, 27, 53],
    id: 970450,
    original_language: "en",
    original_title: "Werewolves",
    overview:
      "초달(supermoon)의 빛이 잠들어 있던 유전자를 활성화시키면서 인간들을 피에 굶주린 늑대인간으로 변하게 하고, 약 10억 명이 사망한 지 1년이 지났다. 그러나 초달이 다시 떠오르며 그 악몽이 되살아난다. 두 명의 과학자가 돌연변이를 막으려 하지만 실패하고, 달빛에 노출된 사람들은 다시 야생의 늑대인간으로 변한다. 거리에는 혼란이 휩싸이고, 과학자들은 맹수로 변한 존재들에게 포위된 가족의 집으로 향하기 위해 고군분투한다.",
    popularity: 1277.066,
    poster_path: "/cRTctVlwvMdXVsaYbX5qfkittDP.jpg",
    release_date: "2024-12-04",
    title: "웨어울브즈",
    video: false,
    vote_average: 6.4,
    vote_count: 170,
  },
  {
    adult: false,
    backdrop_path: "/k24eZq5I3jyz4htPkZCRpnUmBzE.jpg",
    genre_ids: [10749, 18],
    id: 1156593,
    original_language: "es",
    original_title: "Culpa tuya",
    overview:
      "전 세계적인 히트작 '나의 잘못'의 속편. 노아와 닉의 사랑은 둘을 떼어놓으려는 부모님의 노력에도 불구하고 흔들림이 없어 보인다. 하지만 닉의 직업과 노아의 대학 진학은 두 사람의 관계와 레이스테르 가족의 근간을 흔들 새로운 관계로 그들의 삶을 안내한다. 많은 사람이 두 사람 사이를 파괴하려는 가운데 이 둘은 결국 행복을 맞이할 수 있을까?",
    popularity: 1259.594,
    poster_path: "/zuctS3p8Bs9IeYv5ScKeOKp5Na5.jpg",
    release_date: "2024-12-26",
    title: "네 잘못이야",
    video: false,
    vote_average: 7.1,
    vote_count: 837,
  },
  {
    adult: false,
    backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
    genre_ids: [28, 878, 53],
    id: 1035048,
    original_language: "en",
    original_title: "Elevation",
    overview:
      "한 명의 싱글파더와 두 명의 여성이 어린 소년의 생명을 구하기 위해 집이라는 안전한 공간을 떠나 괴물 같은 생명체들과 맞서게 된다.",
    popularity: 1242.49,
    poster_path: "/tnfc0NJ3BzhJrGJhkkEd6MHBdq5.jpg",
    release_date: "2024-11-07",
    title: "엘리베이션",
    video: false,
    vote_average: 6.3,
    vote_count: 322,
  },
  {
    adult: false,
    backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
    genre_ids: [16, 14, 12],
    id: 823219,
    original_language: "lv",
    original_title: "Straume",
    overview:
      "대홍수가 세상을 덮친 뒤, 유일한 피난처가 된 배 한 척을 타고 다양한 동물 친구들과 항해를 시작한 ‘고양이’의 눈부신 모험담",
    popularity: 966.429,
    poster_path: "/kX9gzHyfwXCkTszBcPekQZxPnzP.jpg",
    release_date: "2024-01-30",
    title: "플로우",
    video: false,
    vote_average: 8.4,
    vote_count: 724,
  },
  {
    adult: false,
    backdrop_path: "/dWkdmxIkH9y23s9v1PjQFhTGIwo.jpg",
    genre_ids: [28, 18, 53],
    id: 1043905,
    original_language: "en",
    original_title: "Dirty Angels",
    overview:
      "2021년 미국의 아프가니스탄 철군 당시, 의료 구호 팀으로 위장한 여성 군인들이 납치된 십대 소년·소녀들을 구출하기 위해 다시 투입된다. 이들은 ISIS와 탈레반 사이에 갇힌 피해자들을 구출하는 임무를 맡는다.",
    popularity: 1074.447,
    poster_path: "/3O3qSGmjRGc10hMwFul8WDxKE5t.jpg",
    release_date: "2024-12-11",
    title: "더티 엔젤스",
    video: false,
    vote_average: 6.47,
    vote_count: 118,
  },
  {
    adult: false,
    backdrop_path: "/bx6LoGl8L3hwgOCoD2H8JgIu7uC.jpg",
    genre_ids: [28, 18],
    id: 1235623,
    original_language: "zh",
    original_title: "目中无人 2",
    overview:
      "현상 수배범을 잡으며 사는 맹인 검객 도위. 그의 삶에 고아 장소어가 느닷없이 나타난다. 복수를 도와 달라는 장소어의 끈질긴 부탁에 어쩔 수 없이 곁에 두고 무예를 가르치고, 도위의 닫혀 있던 마음도 서서히 열리게 되는데...",
    popularity: 1015.357,
    poster_path: "/c7MdJDM6nURfQyhvIOcjPaPtwST.jpg",
    release_date: "2024-07-21",
    title: "목중무인 2",
    video: false,
    vote_average: 8,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/rhc8Mtuo3Kh8CndnlmTNMF8o9pU.jpg",
    genre_ids: [53, 28],
    id: 1005331,
    original_language: "en",
    original_title: "Carry-On",
    overview:
      "크리스마스이브, 항공기에 위험한 물건을 실으라는 강요를 받은 공항 보안 요원. 이 위협에서 벗어나려면, 의문의 여행자보다 한 수 앞서 움직여야 한다.",
    popularity: 927.035,
    poster_path: "/moQ4z3yKFwd7CuNqrLINMl1pdp.jpg",
    release_date: "2024-12-05",
    title: "캐리온",
    video: false,
    vote_average: 6.933,
    vote_count: 1608,
  },
  {
    adult: false,
    backdrop_path: "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
    genre_ids: [27, 878],
    id: 933260,
    original_language: "en",
    original_title: "The Substance",
    overview:
      "더 나은 버전의 당신을 꿈꿔본 적 있나요? 당신의 인생을 바꿔줄 신제품 ‘서브스턴스’. ‘서브스턴스’는 또 다른 당신을 만들어냅니다. 새롭고, 젊고, 더 아름답고, 더 완벽한 당신을. 단 한가지 규칙, 당신의 시간을 공유하면 됩니다. 당신을 위한 일주일, 새로운 당신을 위한 일주일, 각각 7일간의 완벽한 밸런스. 쉽죠? 균형을 존중한다면… 무엇이 잘못될 수 있을까요?",
    popularity: 866.5,
    poster_path: "/5TPPefBI1OzWnSQfBkOrv1OFGq5.jpg",
    release_date: "2024-09-07",
    title: "서브스턴스",
    video: false,
    vote_average: 7.127,
    vote_count: 3226,
  },
  {
    adult: false,
    backdrop_path: "/i9bhxhUBFZHorvK81GNKMJGj2Kt.jpg",
    genre_ids: [99],
    id: 1214667,
    original_language: "en",
    original_title: "Making Squid Game: The Challenge",
    overview:
      "《오징어 게임》을 바탕으로 한 리얼리티 시리즈 《오징어 게임: 더 챌린지》. 픽션 드라마가 아슬아슬하고 치열한 서바이벌 예능으로 탄생하기까지, 그 제작 과정을 비하인드 영상으로 만나본다.",
    popularity: 768.358,
    poster_path: "/73vGRE3qpt1Ifb83uDv9JK6vQEB.jpg",
    release_date: "2023-12-06",
    title: "오징어 게임: 더 챌린지 메이킹",
    video: false,
    vote_average: 6.3,
    vote_count: 35,
  },
  {
    adult: false,
    backdrop_path: "/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg",
    genre_ids: [28, 35, 878],
    id: 533535,
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    overview:
      "히어로 생활에서 은퇴한 후, 평범한 중고차 딜러로 살아가던 ‘데드풀’이 예상치 못한 거대한 위기를 맞아 모든 면에서 상극인 ‘울버린’을 찾아가게 되며 펼쳐지는 도파민 폭발 액션 블록버스터.",
    popularity: 854.545,
    poster_path: "/8beFmkVCbl88nqc5CUO7kE5Z2W5.jpg",
    release_date: "2024-07-24",
    title: "데드풀과 울버린",
    video: false,
    vote_average: 7.7,
    vote_count: 6365,
  },
  {
    adult: false,
    backdrop_path: "/6lE2e6j8qbtQR8aHxQNJlwxdmKV.jpg",
    genre_ids: [28, 80, 53],
    id: 974453,
    original_language: "en",
    original_title: "Absolution",
    overview: "",
    popularity: 745.47,
    poster_path: "/2MeQG5Vq8rUnRAa463BZe5GNhVk.jpg",
    release_date: "2024-10-31",
    title: "앱솔루션",
    video: false,
    vote_average: 5.854,
    vote_count: 250,
  },
  {
    adult: false,
    backdrop_path: "/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg",
    genre_ids: [16, 28, 878, 10751],
    id: 1184918,
    original_language: "en",
    original_title: "The Wild Robot",
    overview:
      "우연한 사고로 거대한 야생에 불시착한 로봇 로즈는 주변 동물들의 행동을 배우며 낯선 환경 속에 적응해 가던 중, 사고로 세상에 홀로 남겨진 아기 기러기 브라이트빌의 보호자가 된다. 로즈는 입력되어 있지 않은 새로운 역할과 관계에 낯선 감정을 마주하고 겨울이 오기 전에 남쪽으로 떠나야 하는 브라이트빌을 위해 동물들의 도움을 받아 이주를 위한 생존 기술을 가르쳐준다. 그러나 선천적으로 몸집이 작은 브라이트빌은 짧은 비행도 힘겨워 하는데...",
    popularity: 712.911,
    poster_path: "/8dkuf9IuVh0VZjDTk7kAY67lU0U.jpg",
    release_date: "2024-09-12",
    title: "와일드 로봇",
    video: false,
    vote_average: 8.365,
    vote_count: 3933,
  },
];
